### ISSUE TITLE
Please add to MELPA

### ISSUE THREAD

**Issue by jasonm23** [11111000000/tao-theme-emacs#1]
You'll just need to fork [milkypostman/melpa](/milkypostman/melpa) and add a new recipe.

`.../recipes/tao-theme-emacs`

```lisp
(tao-theme-emacs :repo "11111000000/tao-theme-emacs" :fetcher github)
```

**Comment by jasonm23** [comment]
@11111000000  please let me know if you approve theme released on MELPA, I will take care of it for you.

**Comment by 11111000000** [comment]
I would like to make some improvements to it, but perhaps there is no special reason to wait, I'll do it. Many thanks for reminding me!

**Comment by jasonm23** [comment]
Thank you.

Note, any time you push to **master** it will just upgrade on MELPA.  So you don't need to do anything special to get new versions out.

Of course, if you have breaking changes keep them in a branch until you're ready to merge them back in.

**Comment by 11111000000** [comment]
pull request added, but have not yet confirmed now

**Comment by jasonm23** [comment]
Nice :+1:
