### ISSUE TITLE
flycheck errors are not visible

### ISSUE THREAD

**Issue by scottjacobsen** [11111000000/tao-theme-emacs#12]
There's a flycheck error on line 155, but it isn't visible. Maybe flycheck errors should use inverse video or have a box around them?

<img width="397" alt="screen shot 2016-02-25 at 12 46 46 pm" src="https://cloud.githubusercontent.com/assets/86936/13332156/f163f1d8-dbbd-11e5-9c6e-cf5abf5d3be5.png">

**Comment by 11111000000** [comment]
flycheck not always works correctly, and for me, one of the advantages of the tao-theme - that, even with the lack of mode support, it looks good. But I agree that you can improve it and I am very happy to accept pull requests with unobtrusive changes, welcome
