### ISSUE TITLE
Comment keyword highlighting distracting

### ISSUE THREAD

**Issue by xinranmsn** [11111000000/tao-theme-emacs#13]
I like this theme for its minimalism and non-distracting colors. But when there are quoted keywords in comments, the keywords appear to be extremely distracting because they are bolder, much brighter than the actual code. Would it be a good idea to dim the keywords in comments, or alternatively just make them bold instead of bright?
![screen shot 2016-03-15 at 01 04 57](https://cloud.githubusercontent.com/assets/856507/13769038/42796932-ea4a-11e5-9ae8-f858fce66574.png)

**Comment by 11111000000** [comment]
I agree, fixed

**Comment by 11111000000** [comment]
pull requests are also welcome )
