### ISSUE TITLE
Font size in org-mode is crazy small

### ISSUE THREAD

**Issue by dakrone** [11111000000/tao-theme-emacs#15]
I'm getting a buffer that looks like this:

![screenshot from 2016-06-07 15-41-50](https://cloud.githubusercontent.com/assets/19060/15875658/5e9bd41a-2cc6-11e6-9134-947821c090ab.png)

Any way to get the font to a readable size?

**Comment by 11111000000** [comment]
I can not reproduce it. Share a link to this file, please.

**Comment by 11111000000** [comment]
Perhaps fixed - please check

**Comment by dakrone** [comment]
That seems to have fixed it, thanks! (and thanks for the theme!)

**Comment by hilldr** [comment]
I'm still having this problem after cloning the latest version. Seems to effect src blocks and any line beginning with "#+".

Love the theme. Please fix org mode by making everything the same size. Tride to work on this myself but I can't seem to find where this face is set.

**Comment by 11111000000** [comment]
Thanks for reporting!

You can explore this with `describe-face`, maybe something with `:height ...`, I'll try, and you can help too.

**Comment by hilldr** [comment]
GNU Emacs 24.5.1

**Comment by hilldr** [comment]
I installed from melpa, enabled the theme, and restarted emacs with the theme initialization in my init.el and this seemed to resolve the issue. The font size in src blocks is now the same as the other text.

**Comment by 11111000000** [comment]
Ok.
