### ISSUE TITLE
hs-face is very stark and yellow

### ISSUE THREAD

**Issue by dakrone** [11111000000/tao-theme-emacs#20]
`hs-face` which is used for folds of hidden code is really bright yellow, perhaps it could be a nice grey instead?

![screenshot_2017-01-13_15-38-47](https://cloud.githubusercontent.com/assets/19060/21948149/79ea1f64-d9a6-11e6-91f8-2aa29355598b.png)

`hs-fringe-face` has good coloring, so perhaps it could share the same color

**Comment by 11111000000** [comment]
fixed?

**Comment by dakrone** [comment]
@11111000000 looks good, thanks!
