### ISSUE TITLE
Company completion is dark-on-dark for tao-yang

### ISSUE THREAD

**Issue by dakrone** [11111000000/tao-theme-emacs#21]
![screenshot_2017-02-28_09-23-13](https://cloud.githubusercontent.com/assets/19060/23414736/39d59d3c-fd9a-11e6-981c-493b73c1bd20.png)

In the screenshot above, there is actually text on the line, however the `d-<` (at least the `d` part) is black text on a black background, so it can't be seen.

Additionally, the `proce` part in the company completion popup is black text on a very dark grey background, meaning only the `d` can be seen.

**Comment by 11111000000** [comment]
try now

**Comment by dakrone** [comment]
This seems to be fixed now, thanks!
