### ISSUE TITLE
elfeed support

### ISSUE THREAD

**Issue by semente** [11111000000/tao-theme-emacs#23]
Would be great if you support the faces `elfeed-search-date-face`, `elfeed-search-feed-face` and `elfeed-search-tag-face`.

I've set them to nil to use the "default" face, which is better than the currently one. Check the screenshots to see before and after my customization.

```
(custom-set-faces
 '(elfeed-search-date-face ((t nil)))
 '(elfeed-search-feed-face ((t nil)))
 '(elfeed-search-tag-face ((t nil))))
```

![screenshot from 2017-03-16 23-42-10](https://cloud.githubusercontent.com/assets/29862/24026865/aa6d479c-0aa2-11e7-994e-19cae00e3e53.png)
![screenshot from 2017-03-16 23-38-22](https://cloud.githubusercontent.com/assets/29862/24026862/aa67d352-0aa2-11e7-8821-eaeda4b6fea2.png)
![screenshot from 2017-03-16 23-42-25](https://cloud.githubusercontent.com/assets/29862/24026863/aa692f72-0aa2-11e7-9473-13f6ff055af4.png)
![screenshot from 2017-03-16 23-46-10](https://cloud.githubusercontent.com/assets/29862/24026877/c7789ec2-0aa2-11e7-874b-a19bde917c59.png)

**Comment by semente** [comment]
There is also this guy here:

![screenshot from 2017-03-16 23-47-48](https://cloud.githubusercontent.com/assets/29862/24026936/1fb3c698-0aa3-11e7-8d9c-bf5562b4f118.png)

It's face is `elfeed-search-unread-count-face` and setting it to nil to use the "default" face works for me as well.

**Comment by 11111000000** [comment]
nice!
