### ISSUE TITLE
Error loading theme

### ISSUE THREAD

**Issue by gguimaraesbr** [11111000000/tao-theme-emacs#26]
I'm trying to use the theme but there's an error while loading it: `Symbol’s function definition is void: remove-if`.

If think it has something to do with this [commit](https://github.com/11111000000/tao-theme-emacs/commit/9824d7b0764a77fdf3fa820214641d94583eceb9) but I can't say for sure. I could make it work by explicitly calling `(require 'cl)` before the `load-theme` command. 

Is it the desired behavior?

**Comment by 11111000000** [comment]
Thanks for reporting.
Try now.

**Comment by gguimaraesbr** [comment]
Can confirm it's working after your fix. Thanks!
