### ISSUE TITLE
Excuse my ignorance but how to achieve color-identifiers like on screenshot?

### ISSUE THREAD

**Issue by FilipMiletic** [11111000000/tao-theme-emacs#28]
I am not sure what to do with the _Integration_ part, where do I put it, in `init.el` or somewhere else?

**Comment by terlar** [comment]
It is mentioned in the read-me, it is another package, it is the package `color-identifiers-mode`. See: https://github.com/ankurdave/color-identifiers-mode

**Comment by 11111000000** [comment]
Yes that's right

**Comment by 11111000000** [comment]
`  (use-package color-identifiers-mode
    :diminish (color-identifiers-mode . "≡ ")
    :bind (("C-c hi" . color-identifiers-mode))
    :ensure t
    :defer t
    :config
    ;;(add-hook 'after-init-hook 'global-color-identifiers-mode)
    ;;(remove-hook 'rjsx-mode-hook 'color-identifiers-mode)
    (add-to-list
     'color-identifiers:modes-alist
     `(rjsx-mode . ("[^.][[:space:]]*"
                      "\\_<\\([a-zA-Z_$]\\(?:\\s_\\|\\sw\\)*\\)"
                      (nil font-lock-variable-name-face js2-function-param)))))
`

**Comment by FilipMiletic** [comment]
hmm that's weird I installed that package, but it wasn't working for some reason. I will dig more into `color-identifiers-mode` docs to see what could be the problem. Thanks anyway.

**Comment by 11111000000** [comment]
for some filetypes it didn't show any colors, you can try rainbow-identifiers-mode instead.

**Comment by 11111000000** [comment]
@FilipMiletic ^^^
