### ISSUE TITLE
Tao-yang displays wrong font in minibuffer prompt

### ISSUE THREAD

**Issue by cireu** [11111000000/tao-theme-emacs#35]
I try to use Tao-yang theme in Emacs 27.0 in Windows 10 1803. and I use the moon branch of Spacemacs configuration and I set the "mononoki" as my favourite font. 

By loading themes manually, I add some code to the `user-init` function

```
    (add-to-list 'load-path "~/.emacs.d/tao-theme")
    (add-to-list 'custom-theme-load-path "~/.emacs.d/tao-theme")
    (load-theme 'tao-yang t)
```

Tao-yang shows correctly almost everywhere but the minibuffer prompt of ivy/smex, its font will automatically fallback to the default font of system.
![tim 20181002010816](https://user-images.githubusercontent.com/18224684/46303883-b3d10900-c5df-11e8-8807-3f586584bb03.png)
But if I use the Tao theme, the font can be displayed properly
![tim 20181002011001](https://user-images.githubusercontent.com/18224684/46303970-f0046980-c5df-11e8-85d9-c9b35d7a7470.png)
And I also try Tao-yin and it doesn't work again! Do you have some ideas about it?
Is it a bug of Emacs 27 or Spacemacs moon or my configurations? 
Thanks for your awesome themes!

**Comment by cireu** [comment]
I found that if start emacs from a dump file, it will be properly displayed. Maybe it just a bug of Emacs 27

**Comment by 11111000000** [comment]
@cireu ok, reopen if you sure

**Comment by komikat** [comment]
@cireu its because you haven't set a fixed pitch font, `(set-face-attribute 'fixed-pitch nil :family "Iosevka" )`, solved it for me.
