### ISSUE TITLE
Add tag for MELPA stable

### ISSUE THREAD

**Issue by edwintorok** [11111000000/tao-theme-emacs#37]
Hi!

[MELPA Stable](http://stable.melpa.org/) is the new younger sibling of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be useful if tao-theme could be installed via Stable.

Fortunately it's also really easy to support—all you have to do is define a tag in the `v...` format and you're done. I'd submit a PR if I could, but since tags are global to a project, that's not something possible via PR.

If you're cool with this idea, this should be all you have to do to make it happen:

```sh
$ git tag v1.1.1 092a442f5b5474c901f45ad087f1fbc5ce54112c
$ git push origin v1.1.1
```

(Of course, confirm that 092a442f5b5474c901f45ad087f1fbc5ce54112c is the appropriate commit for the release, but it's the one where the version number was bumped to 1.1.1 so I suspect it is.)

Thanks for your time and consideration!

**Comment by 11111000000** [comment]
Reasonable idea.

Done.

Thanks for caring about!
