### ISSUE TITLE
Screenshots not appearing in README

### ISSUE THREAD

**Issue by m-cat** [11111000000/tao-theme-emacs#38]
Hello, I unfortately do not see any images in the Screenshots compartment.

Best cheers,
m-cat

**Comment by 11111000000** [comment]
Can you add your one? Thank's!

**Comment by 11111000000** [comment]
For us now it look like that
![2018-12-15-234243_1366x768_scrot](https://user-images.githubusercontent.com/977130/50044752-47848280-00c3-11e9-9158-a5483f1b1f20.png)

**Comment by 11111000000** [comment]
for me it looks like:
![2018-12-15-234456_1366x768_scrot](https://user-images.githubusercontent.com/977130/50044764-8a465a80-00c3-11e9-972d-7e41e7185ec5.png)

**Comment by 11111000000** [comment]
theme in process
![2018-12-16-001810_1366x768_scrot](https://user-images.githubusercontent.com/977130/50045090-34c07c80-00c8-11e9-9d4e-0eaa2cb182da.png)

**Comment by 11111000000** [comment]
Web dev
![2018-12-16-004705_1366x768_scrot](https://user-images.githubusercontent.com/977130/50045345-32602180-00cc-11e9-8651-e5efa8031934.png)

**Comment by 11111000000** [comment]
magit log fixes see in recent commit

**Comment by 11111000000** [comment]
@m-cat fixed with https://www.reddit.com/r/emacs/comments/9v7ut1/screenshot_showcase_2018/
