### ISSUE TITLE
`(:line-width 2 :style pressed-button)` causes misalignment in `org-mode` `clocktable`s

### ISSUE THREAD

**Issue by drc-bsorenson** [11111000000/tao-theme-emacs#39]
Line 720 in `tao-theme.el`, `(org-checkbox-statistics-todo                    ((t (:foreground ,color-11 :box (:line-width 2 :style pressed-button) :inherit fixed-pitch))))` causes misaligned column separators in rows like the second-to-last in the `org-mode` `clocktable` below. Please consider changing this setting to something else. Maybe a highlight instead of a `pressed-button`?
```
  | Headline               | Time   |      |      |
  |------------------------+--------+------+------|
  | *Total time*           | *8:00* |      |      |
  |------------------------+--------+------+------|
  | Some Project           | 8:00   |      |      |
  | \_  Some Task [0/2][0%] |        | 8:00 |      |
  | \_    Some Sub Task    |        |      | 8:00 |

```

**Comment by 11111000000** [comment]
![2018-12-23-014827_1366x768_scrot](https://user-images.githubusercontent.com/977130/50377271-0822dc80-0655-11e9-93ab-3d41bc44f54c.png)
?

**Comment by drc-bsorenson** [comment]
Love the theme, thanks for changing this!
