### ISSUE TITLE
Colors seem off on macOS when using `tao-yang`

### ISSUE THREAD

**Issue by apc** [11111000000/tao-theme-emacs#40]
Trying out `tao-theme` on Emacs 26.1 in macOS Mojave. Colors appear different than intended and cannot figure out why. Using Apple's Digital Color Meter on the screenshot in the `Readme` file I get #f1f1f1 as the background. Using it on Emacs, the background color reads #FFFF9. (If I do `describe-face` for `Default face`, the background color is listed there as #FFFF8.) 
<img width="1267" alt="Screen Shot 2019-04-01 at 3 51 46 PM" src="https://user-images.githubusercontent.com/350504/55355370-15dad000-5496-11e9-81da-4e5bf71cb6da.png">

I have disabled every other theme. I have no idea what else could be messing things up. I'm using the `emacs-mac` `brew` formula. I also tried using the `emacs-plus` formula but got the same results. I'm new to Emacs, so my apologies if there's some obvious issue here I'm just not seeing.

**Comment by railwaycat** [comment]
This is because of `tao-theme-use-sepia` is enabled by default. You can set it to `nil` or disable it by customize.

**Comment by apc** [comment]
Might be worth making this clearer on the documentation? It's a bit confusing that the default behavior does not correspond to what the screenshots would suggest.
