### ISSUE TITLE
Which fonts are set in the light version?

### ISSUE THREAD

**Issue by jayesh-bhoot** [11111000000/tao-theme-emacs#41]
The `r` looks fabulous!

**Comment by 11111000000** [comment]
`(defun update-font-settings ()
  (interactive)
  (set-face-attribute 'default nil :family "Fira Mono" )
  (set-face-attribute 'fixed-pitch nil :family "Fira Code" )
  (set-face-attribute 'variable-pitch nil :family "Fira Sans" )
  (set-face-attribute 'org-level-1 nil :family "Fira Sans")
  )

(add-hook 'after-load-theme-hook (lambda () (update-font-settings)))

(update-font-settings)
`
