### ISSUE TITLE
Please add a Free Software/Document License

### ISSUE THREAD

**Issue by agraul** [11111000000/tao-theme-emacs#43]
Hi,

I realized this repo does not contain a LICENSE file and also does not specify any term under which others are allowed to download, share, change this theme. I assume this is just an oversight, but please add a license to the project. Since you have already accepted contributions from others, you are not the only copyright holder of these files anymore and need to ask everyone with a meaningful contribution to agree to the license terms.

If you don't know which license to choose, take a look at https://choosealicense.com/ and see if you like any of them :)

**Comment by rekado** [comment]
The file itself contains a license notice:
https://github.com/11111000000/tao-theme-emacs/blob/master/tao-theme.el#L15

**Comment by alexandergraul** [comment]
You are right @rekado, I missed that. Happy to realize that the theme is free-software-licensed.

It might still be worth it to include the license text in the repo, that way GitHub will display it and it is not as easy to miss. The license notice also mentions that "this program" should distribute the text.

**Comment by 11111000000** [comment]
done
