### ISSUE TITLE
Colors doesn't appear to be same as in screenshot with Emacs-27.1 on Linux

### ISSUE THREAD

**Issue by codesoverhill** [11111000000/tao-theme-emacs#44]
Am using Emacs 27.1 with Doom Emacs on Linux. Background colour for Yin is "#292617" unlike the screenshot which is "#171717". Is there a config missing from my side?

![bg](https://user-images.githubusercontent.com/28491132/96020216-4e20e400-0e6b-11eb-98e9-67af43a0d184.png)

For comparison Yang too is not same as screenshot

![yang](https://user-images.githubusercontent.com/28491132/96020744-1f573d80-0e6c-11eb-9881-f39903715374.png)

Thank you.

**Comment by slotThe** [comment]
The screenshots are taken with `tao-theme-use-sepia` set to `nil`, but it's set to `t` by default now.  Try doing

``` emacs-lisp
(setq tao-theme-use-sepia nil)
```

**Comment by codesoverhill** [comment]
> The screenshots are taken with `tao-theme-use-sepia` set to `nil`, but it's set to `t` by default now. Try doing
> 
> ```emacs-lisp
> (setq tao-theme-use-sepia nil)
> ```

Ah. Thank you.
