### ISSUE TITLE
Buffer name is almost invisible.

### ISSUE THREAD

**Issue by jxy** [11111000000/tao-theme-emacs#5]
Somehow the face, `mode-line-buffer-id`, gets the foreground color close to the background.  This makes the buffer name almost invisible on the mode line.

**Comment by 11111000000** [comment]
normally I can't see this, because of custom powerline theme. 
now fixed. Thank you for feedback!

**Comment by 11111000000** [comment]
if it's ok now, you can close the issue yourself.

**Comment by jxy** [comment]
Thanks for the quick response.
Do you plan to publish your powerline theme?

**Comment by 11111000000** [comment]
[here](https://github.com/11111000000/emacs-d) you can see it

**Comment by jxy** [comment]
Just updated the theme.  It seems the buffer names are again invisible without powerline.

**Comment by 11111000000** [comment]
thank you, fixed again )
