### ISSUE TITLE
Ediff visibility

### ISSUE THREAD

**Issue by rymndhng** [11111000000/tao-theme-emacs#6]
Visibility is pretty bad using ediff.

See:

![screen shot 2015-09-14 at 12 16 12](https://cloud.githubusercontent.com/assets/1694040/9859257/74a1b87e-5ada-11e5-89c7-b631c147c22a.png)

**Comment by 11111000000** [comment]
Thanks for reporting, and if you can fix this - pull requests are welcome!

**Comment by 11111000000** [comment]
Can you explain of how it should look like?

**Comment by 11111000000** [comment]
![ediff](https://cloud.githubusercontent.com/assets/977130/21799786/a985e45e-d755-11e6-9290-256348c86f33.png)

**Comment by 11111000000** [comment]
![ediff](https://cloud.githubusercontent.com/assets/977130/21799858/f922975a-d755-11e6-9080-3b856a78aad8.png)

**Comment by rymndhng** [comment]
Sorry for the lack of response 🙏 looks awesome though :)
