### ISSUE TITLE
Mode Line has a font too small.

### ISSUE THREAD

**Issue by CestDiego** [11111000000/tao-theme-emacs#7]
[![alt](https://i.imgur.com/09iiBoM.png)](https://i.imgur.com/09iiBoM.png)

This is how it looks on spacemacs. (spaceline package on MELPA for the mode line) and this is how it looks with any other theme

[![alt](https://i.imgur.com/YgH7Cua.png)](https://i.imgur.com/YgH7Cua.png)

**Comment by 11111000000** [comment]
Fixed by abd63d55a78cbc797c3a458200207131893900a0 
Thanks for reporting!
