### ISSUE TITLE
Org mode Source Blocks Too tiny

### ISSUE THREAD

**Issue by CestDiego** [11111000000/tao-theme-emacs#8]
The source blocks in org mode are too tiny, I liked it when the #+begin_src and #+end_src lines were small because it lets you focus on the code, but now the Code inside a source block is also too small, not worth it.

[![alt](https://i.imgur.com/G0Ul4Ui.png)](https://i.imgur.com/G0Ul4Ui.png)

**Comment by 11111000000** [comment]
Thanks for reporting, and if you can fix this - pull requests are welcome!

**Comment by 11111000000** [comment]
fixed

**Comment by CestDiego** [comment]
thank you :)
